name: anime_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <3.16.2'
dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  equatable: ^2.0.5
  go_router: ^10.0.0
  video_player: ^2.7.0
  chewie: ^1.7.5
  path_provider: ^2.1.1
  provider: ^6.0.5
  dartz: ^0.10.1
  connectivity_plus: ^4.0.2
  get_it: ^7.6.4
  flutter_cache_manager: ^3.3.1
  bloc_concurrency: ^0.2.2
  sqflite: ^2.3.0
  http: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/Raleway-Italic.ttf
          style: italic